In [2]:
from PIL import Image
import numpy as np

#example image from Train/SEM/
img = Image.open("/data/jhkim/samsung/AI_challenge_data/Train/SEM/20201001_202940_NE142400C_RAE01_1_S01_M0005-01MS_3_itr0.png")
print(type(img))
img.show()

<class 'PIL.PngImagePlugin.PngImageFile'>


In [3]:
#numpy2img
#img = Image.fromarray(img_numpy, 'GREY')
#save iamge
#img.save(PATH)

img_numpy = np.array(img)
print(img_numpy.shape)
print(img_numpy[25][25])

display-im6.q16: unable to open X server `' @ error/display.c/DisplayImageCommand/432.


(66, 45)
50


In [4]:
%matplotlib inline
import matplotlib
import matplotlib.pyplot as plt
import torch
from torch.utils.data import Dataset, DataLoader
import torchvision
from torchvision import transforms

In [5]:
import os
train_SEMimglist = os.listdir("/data/jhkim/samsung/AI_challenge_data/Train/SEM")
train_depthimglist = os.listdir("/data/jhkim/samsung/AI_challenge_data/Train/Depth")
len(train_SEMimglist)
len(train_depthimglist)
print(train_SEMimglist[0])
print(train_depthimglist[0])

20201219_130240_NE142400C_RAA0J_2_S02_M0098-01MS_0_itr2.png
20210104_183453_NE142400C_RAA0N_3_S11_M0152-01MS_1.png


In [6]:
trans = transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.5,),(0.5,))])
trans_wo_Norm = transforms.ToTensor()


In [7]:
SEM_root = "/data/jhkim/samsung/AI_challenge_data/Train/SEM/"
depth_root = "/data/jhkim/samsung/AI_challenge_data/Train/Depth/"

class img_dataset(Dataset):
    def __init__(self, file_list, transform):
        self.file_list = file_list
        self.transform = transform
    def __len__(self):
        return len(self.file_list)
    def __getitem__(self, index):
        img_path = self.file_list[index]
        img = Image.open(SEM_root + img_path)
        img_transformed = self.transform(img)

        return img_transformed, img_path

In [44]:
img_path = train_SEMimglist[0]
img = Image.open(SEM_root + img_path)
#img_transformed = trans_wo_Norm(img)
img_transformed = np.array(img)
print(img_transformed)

[[132 124 131 ... 136 132 124]
 [129 124 139 ... 139 137 131]
 [130 130 147 ... 135 132 137]
 ...
 [127 121 141 ... 134 120 121]
 [124 125 133 ... 132 122 128]
 [125 137 133 ... 133 137 122]]


In [45]:
img_path = train_SEMimglist[1]
img = Image.open(SEM_root + img_path)
#img_transformed = trans_wo_Norm(img)
img_transformed2 = np.array(img)
print(img_transformed-img_transformed2)

[[  8   1   8 ...   8   5   0]
 [  3 253  16 ...  18  19   6]
 [  5 255  21 ...   7  10   2]
 ...
 [  5   3  15 ...   0 240 235]
 [  5   9   4 ... 247 245 251]
 [254  14   2 ... 252   3 242]]


In [48]:
img_path = train_depthimglist[0]
img = Image.open(depth_root + img_path)
#img_transformed = trans_wo_Norm(img)
img_transformed = np.array(img)
print(img_transformed[:][20])

[167 167 167 167 167 167 167 167 167 147 101  68  56  47  39  33  27  23
  20  17  16  15  14  14  14  14  15  16  17  20  23  30  40  54  69 122
 167 167 167 167 167 167 167 167 167]


In [20]:
train_dataset = img_dataset(file_list = train_SEMimglist, transform=trans)
print(len(train_dataset))
train_dataloader = DataLoader(train_dataset, batch_size=3, shuffle=True)

batch_iterator = iter(train_dataloader)
images, img_paths = next(batch_iterator)

print(images.size())
print(len(img_paths))
print(img_path[0])
img_path[0][:-9]+'.png'

40000
torch.Size([3, 1, 66, 45])
3
20201219_130240_NE142400C_RAA0J_2_S02_M0271-01MS_3_itr3.png


'20201219_130240_NE142400C_RAA0J_2_S02_M0271-01MS_3.png'

In [13]:
for j, (image, img_path) in enumerate(train_dataloader):
    print(image.size())
    print(img_paths)

torch.Size([3, 1, 66, 45])
('20210113_195504_NE142400C_RAM1NI_1_S14_M0087-01MS_3_itr2.png', '20210320_205830_NE142400C_RAA1V_1_S02_M0400-01MS_2_itr3.png', '20210109_015451_NE142400C_RAA0W_1_S05_M0082-01MS_2_itr1.png')
torch.Size([3, 1, 66, 45])
('20210113_195504_NE142400C_RAM1NI_1_S14_M0087-01MS_3_itr2.png', '20210320_205830_NE142400C_RAA1V_1_S02_M0400-01MS_2_itr3.png', '20210109_015451_NE142400C_RAA0W_1_S05_M0082-01MS_2_itr1.png')
torch.Size([3, 1, 66, 45])
('20210113_195504_NE142400C_RAM1NI_1_S14_M0087-01MS_3_itr2.png', '20210320_205830_NE142400C_RAA1V_1_S02_M0400-01MS_2_itr3.png', '20210109_015451_NE142400C_RAA0W_1_S05_M0082-01MS_2_itr1.png')
torch.Size([3, 1, 66, 45])
('20210113_195504_NE142400C_RAM1NI_1_S14_M0087-01MS_3_itr2.png', '20210320_205830_NE142400C_RAA1V_1_S02_M0400-01MS_2_itr3.png', '20210109_015451_NE142400C_RAA0W_1_S05_M0082-01MS_2_itr1.png')
torch.Size([3, 1, 66, 45])
('20210113_195504_NE142400C_RAM1NI_1_S14_M0087-01MS_3_itr2.png', '20210320_205830_NE142400C_RAA1V_1_S